caesar_txt = 'U kriptografiji, Cezarova šifra jedan je od najjednostavnijih i najrasprostranjenijih načina šifriranja. To je tip šifre zamjene (supstitucije), u kome se svako slovo otvorenog teksta zamjenjuje odgovarajućim slovom abecede, pomaknutim za određeni broj mjesta. Na primjer, s pomakom 3, A se zamjenjuje slovom D, B slovom E itd. Ova metoda je dobila ime po Juliju Cezaru, koji ju je koristio za razmjenu poruka sa svojim generalima.'

supstitution_txt = 'Supstitucijska šifra elemente p otvorenog teksta zamjenjuje (supstituira) elementima šifrata c ovisno o ključu k. Element otvorenog teksta može biti slovo (znak) ili niz slova (znakova). Znakovi se pretvaraju u odgovarajuće brojčane vrijednosti u rasponu 1-26 te se šifrat (otvoreni tekst) dobiva modularnim zbrajanjem (oduzimanjem) prema formuli:\n\n E(k,p)=(p+k) mod 𝒞 \n\n Prije šifriranja potrebno je odabrati ključ u rasponu 1-26.'

vigenere_txt = 'Vigenèreova šifra je metoda šifriranja abecednog teksta korištenjem serije Cezarovih šifri, zasnovanih na slovima ključa. Ovo je jednostavni oblik šifre polialfabetske supstitucije. \n\nZnakovi otvorenog teksta i ključa pretvaraju se u odgovarajuće brojčane vrijednosti u rasponu 1-26 te se šifrat dobiva indeksiranjem Viegenereovog kvadrata dobivenim brojčanim vrijednostima.\n\nPrije šifriranja potrebno je unesti ključnu riječ koja predstavlja ključ šifriranja. \n\nUz klasično šifriranje ponavljanjem ključne riječi otvoreni tekst moguće je šifrirati metodom "autoključa" klikom na polje "autokey" koje se nalazi na dnu prozora. Šifriranje autoključem znači da će se nakon ključne riječi za šifriranje koristiti znakovi otvorenog teksta.'

playfair_txt = 'Playfairova šifra je supstitucijski kriptosustav koji supsituciju vrši nad parovima slova (bigramima) umjesto da supstituira svako slovo pojedinačno. \n Prilikom šifriranja, otvoreni tekst se najprije podijeli na blokove od po dva slova (bigrame), uzimajući u obzir da se nijedan blok ne sastoji od dva jednaka slova, kao i da je duljina teksta paran broj (prema potrebi umeće se slovo X). Dobiveni bigrami šifriraju se prema sljedeća tri pravila (ovisno o položaju slova u matrici):\n\n Slova se nalaze u istom retku: zamjenjujemo ih ciklički slovima koja se nalaze za jedno mjesto udesno odgovarajućih slova bigrama.\n\n Slova se nalaze u istom stupcu: zamjenjujemo ih ciklički slovima koja se nalaze za jedno mjesto ispod odgovarajućih slova bigrama.\n\n Slova nisu u istom retku ili stupcu: promatramo pravokutnik kojeg određuju ta dva slova te ih zamjenjujemo s preostala dva vrha tog pravokutnika tako što se zamjenjuju slova vrhova istog retka.'

hill_txt = 'Hillov kriptosustav je poligrafski supstitucijski kriptosustav utemeljen na linearnoj algebri. Zamjenjuje m uzastopnih slova otvorenog teksta s m slova u šifratu. Ukoliko broj slova otvorenog teksta nije djeljiv sa m poruku treba nadopuniti kako bi se mogla podijeliti na blokove od m slova.\nMatrica K koja se koristi kao ključ mora biti invertibilna budući da se prilikom dešifriranja koristi njezin inverz. Elementi otvorenog teksta pretvaraju se u odgovarajuće brojčane vrijednosti u rasponu 1-26, šifriranje se zatim vrši rješavanjem m linearnih jednadžbi, tj. množenjem svakog bloka od m slova (vektor P) s invertibilnom matricom veličine m x m koja predstavlja ključ.'

transposition_txt = 'Transpozicijski kriptosustavi permutiraju elemente otvorenog teksta, tj. mijenja se međusobni položaj elemenata otvorenog teksta, za razliku od supstitucijskih kriptosustava koji elemente otvorenog teksta preslikavaju u elemente šifrata. \n Najčešće upotrebljavan transpozicijski kriptosustav je tzv. stupčana transpozicija. Otvoreni tekst se po recima upisuje u pravokutnik n x (p/n) elemenata, a zatim se poruka iščitava po stupcima ali sa izmijenjenim redoslijedom stupaca (ovisno o ključu). Ukoliko posljednji redak nije ispunjen do kraja, on se popunjava proizvoljnim slovima koja neće promijeniti sadržaj poruke (npr. X).\n\nKljuč se unosi u brojčanom obliku. Ukoliko je ključ duljine 5 brojeva potrebno je da su unutar ključa uključene znamenke od 1 do 5. Znamenke se upisuju proizvoljnim redoslijedom te predstavljaju redoslijed isčitavanja stupaca matrice koja se formira prilikom šifriranja.'

onetimepad_txt = 'Jednokratna bilježnica je teoretski apsolutno siguran kriptosustav odnosno nemoguće ga je razbiti kriptoanalizom. Za svaki otvoreni tekst generira se novi potpuno nasumičan ključ jednake duljine. Otvoreni tekst, ključ i šifrat mogu biti niz bitova (znakova) duljine n, pri čemu se šifrat dobiva primjenom logičke operacije „isključivo ili (XOR)“ ili modularnim zbrajanjem između odgovarajućih bitova (znakova) otvorenog teksta i ključa.\n\n Bitno je napomenuti kako ovdje implementirana jednokratna bilježnica NIJE u potpunosti sigurna jer su generirani ključevi PSEUDO NASUMIČNI.'

des_txt = 'DES ili Data Encryption standard je simetričan blokovni kriptosustav koji je prije bio najrašireniji i najpouzdaniji sustav za šifriranje podataka.\n\nDES obrađuje 64-bitne blokove podataka. Ključ šifriranja predaje se u heksadecimalnom obliku i također mora biti veličine 64 bita.\n\nOtvoreni tekst moguće je unesti u tekstualnom ili heksadecimalnom obliku označavanjem odgovarajućeg odabirnog okvira.'